---
title: "비정규"
author: "박진아"
date: '2021 4 26 '
output: word_document
---

```{r}
진보_지지율 <-read.csv("제 6회 전국동시지방선거 (2014).csv", encoding='CP949')
지역_범죄율<-read.csv('범죄발생_지역_20210423233330.csv')
지역_자살률<-read.csv('지역별 자살률.csv') 
지역_범죄율<-지역_범죄율[,c(-1,-3)]
지역_자살률<-지역_자살률[,c(-2,-3)]
names(지역_범죄율)<-c('region','범죄_data')
names(지역_자살률)<-c('region','자살_data')
names(진보_지지율)<-c('region','진보_data')

핵심_데이터<-left_join(지역_범죄율,진보_지지율,by='region')
핵심_데이터<-left_join(핵심_데이터,지역_자살률,by='region')
핵심_데이터[is.na(핵심_데이터)] <- 77.96
```

```{r}
quantile(핵심_데이터$진보_data)
핵심_데이터$data[핵심_데이터$진보_data<46.905]<-'1' #25%와 50% 사이 임의의 값
핵심_데이터$data[핵심_데이터$진보_data<52.94&핵심_데이터$진보_data>=46.905]<-'2'#50%와 70% 사이 임의의 값
핵심_데이터$data[핵심_데이터$진보_data>=52.94]<-'3'
View(핵심_데이터)
핵심_데이터$data.factor<-factor(핵심_데이터$data,levels=c(1,2,3),labels=c('진보 지지율이 낮은 집단','진보 지지율이 중간인 집단 ','진보 지지율이 높은 집단 '))
str(핵심_데이터$data.factor)
```

```{r}
kruskal.test(범죄_data ~ data, data=핵심_데이터)  #비모수 분산분석 
```


```{r warning=FALSE}
# 비모수적 사후검증 Mann-Whitney test by bonferroni's method
library(pgirmess)  
kruskalmc(핵심_데이터$범죄_data, 핵심_데이터$data)
```