---
title: "아노바 데이터 전처리"
author: "ddd"
date: '2021 4 23 '
output: html_document
---

```{r}
library(dplyr)
library(tibble)
library(gmodels)
library(ggplot2)
library(tidyr)
```

```{r}
# 불필요한 열 삭제 및 필요한 데이터 합치기
진보_지지율<-read.csv('제 6회 전국동시지방선거 (2014).csv ')
View(진보_지지율)
지역_범죄율<-read.csv('범죄발생_지역_20210423233330.csv')
지역_자살률<-read.csv('지역별 자살률.csv')
View(지역_자살률)
View(지역_범죄율)
지역_범죄율<-지역_범죄율[,c(-1,-3)]
지역_자살률<-지역_자살률[,c(-2,-3)]
names(지역_범죄율)<-c('region','범죄_data')
names(지역_자살률)<-c('region','자살_data')
names(진보_지지율)<-c('region','진보_data')
핵심_데이터<-inner_join(지역_범죄율,진보_지지율,by='region')
View(핵심_데이터)
핵심_데이터<-left_join(핵심_데이터,지역_자살률,by='region')
View(핵심_데이터)
```
```{r}
# 범죄 관련 독립변수 만들기
quantile(핵심_데이터$진보_data)
핵심_데이터$data[핵심_데이터$진보_data<46.54]<-'1' #25%와 50% 사이 임의의 값
핵심_데이터$data[핵심_데이터$진보_data<51.4712&핵심_데이터$data>=46.54]<-'2'#50%와 70% 사이 임의의 값
핵심_데이터$data[핵심_데이터$진보_data>=51.4712]<-'3'
View(핵심_데이터)
핵심_데이터$data.factor<-factor(핵심_데이터$data,levels=c(1,2,3),labels=c('진보 지지율이 낮은 집단','진보 지지율이 중간인 집단 ','진보 지지율이 높은 집단 '))
str(핵심_데이터$data.factor)
# 범죄율 종속변수는 핵심_데이터$Crime_data 사용하면 될듯../?
```
