---
title: "감정분석"
author: "김유은"
date: '2021 4 18 '
output: html_document
---
```{r}
library(tm)
library(ggplot2)
library(rtweet)
library(wordcloud2)
library(wordcloud)
library(syuzhet)
library(stringr)
library("rJava")
#install.packages("memorise")
library(KoNLP)
library(dplyr)
#install.packages("RColorBrewer")#색상
#install.packages("extrafont")#폰트
library(RColorBrewer)
library(extrafont)
source(file = "TwitterAPIKey.R", echo = FALSE)

#트위터 #더불어민주당
keyword1 <- enc2utf8("#더불어민주당")
trendingTweets = search_tweets(keyword1, n=1000, lang ="ko")
save(trendingTweets, file = "더불어.Rda")
load("더불어.Rda")
length(trendingTweets)
txt <- trendingTweets # #더불어민주당 텍스트 불러오기 
txt_df<- as.data.frame(txt) #데이터프레임으로 변경
head(txt_df$text)
View(trendingTweets)
useNIADic()#사전설정


```

```{r}
useSejongDic()
options(mc.cores=1)


i <- 9 #첫번째 트윗으로 지정해놓고 필요없는 단어 지우기 
txt_df$text[i]
nohandles <- str_replace_all(txt_df$text, "@\\w+", "")
nohandles[i]
wordCorpus <- Corpus(VectorSource(nohandles))#코퍼스형태로 바꾸면 티맵 쓸수잇음
wordCorpus[[i]]$content
wordCorpus <- tm_map(wordCorpus, removeWords, c("https"))
wordCorpus[[i]]$content
 #smart하면 더 광범위하게 지울수잇음
wordCorpus <- tm_map(wordCorpus, removePunctuation)#티맵 패키지
wordCorpus[[i]]$content
wordCorpus <- tm_map(wordCorpus, removeNumbers) 
wordCorpus[[i]]$content
wordCorpus <- tm_map(wordCorpus, stripWhitespace)
wordCorpus[[i]]$content




  
tweetSentiments <- get_sentiment(content(wordCorpus), method = "syuzhet")
get_sentiment_dictionary(dictionary = 'syuzhet')
tweets <- cbind(txt_df, tweetSentiments)
names(txt_df)
names(tweets)
tweets$sentiment <- sapply(tweets$tweetSentiments,encodeSentiment)
head(tweets, n = 1)

#plot by sentiment score
qplot(tweets$tweetSentiments) + theme(legend.position="none")+
  xlab("Sentiment Score") +
  ylab("Number of tweets") + 
  ggtitle("Tweets by Sentiment Score") 
```